os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake cmake-data cpanminus libperl-dev mercurial ninja-build perl valgrind
install:
    - which python3
    - sudo cpanm --notest Dist::Zilla Env::Path Games::Solitaire::Verify::Solution IO::All Inline Inline::C Perl::Tidy Pod::Weaver::Section::Support Test::Code::TidyAll Test::CPAN::Changes Test::Differences Test::Kwalitee Test::Pod Test::Pod::Coverage Test::TrailingSpace Test::Trap
    - wget http://web-cpan.shlomifish.org/downloads/libtap-1.12.0.tar.bz2
    - tar -xvf libtap-1.12.0.tar.bz2
    - ( mkdir B && cd B && cmake ../libtap-1.12.0 && make && sudo make install )
    - ( a="$(pwd)"; tgt="black-hole-solitaire/c-solver/cmake/"; mkdir B2 && cd B2 && hg clone https://bitbucket.org/shlomif/shlomif-cmake-modules && cd shlomif-cmake-modules/shlomif-cmake-modules && cp -f "$(pwd)"/Shlomif_Common.cmake "$a"/"$tgt"/ )
    - "( cd black-hole-solitaire/Games-Solitaire-BlackHole-Solver/ && dzil authordeps --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 sudo cpanm --quiet --notest )"
    - "( cd black-hole-solitaire/Games-Solitaire-BlackHole-Solver/ && dzil listdeps --author --missing | grep -vP '[^\\w:]' | xargs sudo cpanm --verbose --notest )"
perl:
    - "5.22"
python:
    - "3.5"
script: "perl black-hole-solitaire/CI-testing/continuous-integration-testing.pl"
