---
# Shamelessly taken from https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/blob/master/.appveyor.yml
# Thanks!
install:
    - choco install strawberryperl -version 5.20.1.1
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - perl -v
    - if not exist C:\Perl5 mkdir C:\Perl5
    - SET PATH=C:\msys64\bin;C:\Perl5\bin;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - SET PERL5LIB=C:/Perl5/lib/perl5
    - SET PERL_LOCAL_LIB_ROOT=C:/Perl5
    - SET PERL_MB_OPT=--install_base C:/Perl5
    - SET PERL_MM_OPT=INSTALL_BASE=C:/Perl5
    - cpanm --notest Dist::Zilla IO::All Test::Differences Test::Trap Env::Path Games::Solitaire::Verify::Solution Inline::C Inline Pod::Coverage::TrustPod Pod::Weaver::Section::Support Test::CPAN::Changes Test::Pod::Coverage Test::Pod Test::TrailingSpace
    - cd black-hole-solitaire
    - mkdir B
    - cd B
    - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    - perl ..\c-solver\Tatzer --gen="MSYS Makefiles"
    - cd ..\..
    - cd black-hole-solitaire\Games-Solitaire-BlackHole-Solver
    - dzil authordeps --missing | cpanm -n
    - dzil listdeps   --missing | cpanm -n
# TODO : add the build/test of the rest of the cmake C version.

build: off

test_script:
    - dzil test -v --all

cache:
    - C:\Perl5

shallow_clone: true

